services:
  wemotoo-crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    # env_file:
    # - .env.prod
    # volumes:
    # For development, you can mount source code
    # - .:/app
    # - /app/node_modules
    tty: true
    stdin_open: true
    restart: unless-stopped
