services:
  wemotoo-crm:
    build:
      context: .
      dockerfile: Dockerfile
      # Force amd64 for Digital Ocean deployment
      platforms:
        - linux/amd64
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    # env_file:
    # - .env.prod
    tty: true
    stdin_open: true
    restart: unless-stopped
