version: '3.8'

services:
  wemotoo-crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      # For development, you can mount source code
      # - .:/app
      # - /app/node_modules
    restart: unless-stopped

  # Development service with hot reload
  wemotoo-crm-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    command: bun run start:local
    restart: unless-stopped
