services:
  wemotoo-crm:
    build:
      context: .
      dockerfile: Dockerfile
      # Use native architecture for faster local development
      platforms:
        - linux/arm64 # For Apple Silicon development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    volumes:
      # For development hot-reloading
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    restart: unless-stopped
