export const SETTING_CODE = {
	MERCHANT_ID: 'MerchantId',
	MERCHANT_NAME: 'MerchantName',
	MERCHANT_THUMBNAIL: 'MerchantThumbnail',
	MERCHANT_BANNER: 'MerchantBanner',
	MERCHANT_PACKAGE: 'MerchantPackage',
	MERCHANT_ACCOUNT_STATUS: 'MerchantAccountStatus',
	MERCHANT_COMPANY_NAME: 'MerchantCompanyName',
	MERCHANT_COMPANY_SSM: 'MerchantCompanySsm',
	MERCHANT_COMPANY_EMAIL_ADDRESS: 'MerchantCompanyEmailAddress',
	MERCHANT_CONTACT_PERSON: 'MerchantContactPerson',
	MERCHANT_CONTACT_NO: 'MerchantContactNo',
	MERCHANT_JOINED_DATE: 'MerchantJoinedDate',
	MERCHANT_EXPIRED_DATE: 'MerchantExpiredDate',
	MERCHANT_ADDRESS_1: 'MerchantAddress_1',
	MERCHANT_ADDRESS_2: 'MerchantAddress_2',
	MERCHANT_ADDRESS_CITY: 'MerchantAddressCity',
	MERCHANT_ADDRESS_COUNTRY: 'MerchantAddressCountry',
	MERCHANT_ADDRESS_STATE: 'MerchantAddressState',
	MERCHANT_ADDRESS_POSTAL_CODE: 'MerchantAddressPostalCode',
};
