import { API_PATH } from 'wemotoo-common';

export const Routes = {
	Images: {
		Upload: () => `${API_PATH.IMAGES}/upload`,
		UploadMultiple: () => `${API_PATH.IMAGES}/upload-multiple`,
	},
	Auth: {
		Login: () => `${API_PATH.AUTH}/login`,
		Verify: () => `${API_PATH.AUTH}/verify`,
		Logout: () => `${API_PATH.AUTH}/logout`,
		PasswordReset: () => `${API_PATH.AUTH}/password-reset`,
		PasswordResetValidate: () => `${API_PATH.AUTH}/password-reset/validate`,
		PasswordResetConfirm: () => `${API_PATH.AUTH}/password-reset/confirm`,
	},
	Countries: {
		Single: (iso2: string) => `${API_PATH.COUNTRIES}/${iso2}`,
		Many: () => `${API_PATH.COUNTRIES}/`,
		Update: (iso2: string) => `${API_PATH.COUNTRIES}/${iso2}`,
	},
	Currencies: {
		Single: (code: string) => `${API_PATH.CURRENCIES}/${code}`,
		Many: () => `${API_PATH.CURRENCIES}/`,
		Update: (code: string) => `${API_PATH.CURRENCIES}/${code}`,
	},
	Customers: {
		Single: (cust_no: string) => `${API_PATH.CUSTOMERS}/${cust_no}`,
		Many: () => `${API_PATH.CUSTOMERS}/`,
	},
	Products: {
		Create: () => `${API_PATH.PROD}/`,
		Single: (code: string) => `${API_PATH.PROD}/${code}`,
		Many: () => `${API_PATH.PROD}/`,
		Update: (code: string) => `${API_PATH.PROD}/${code}`,
		Delete: (code: string) => `${API_PATH.PROD}/${code}`,
		DeleteVariant: (code: string, variant_code: string) => `${API_PATH.PROD}/${code}/variants/${variant_code}`,
		Restore: (code: string) => `${API_PATH.PROD}/restore/${code}`,
	},
	ProductBrands: {
		Create: () => `${API_PATH.PROD_BRANDS}/`,
		Single: (code: string) => `${API_PATH.PROD_BRANDS}/${code}`,
		Many: () => `${API_PATH.PROD_BRANDS}/`,
		Update: (code: string) => `${API_PATH.PROD_BRANDS}/${code}`,
		Delete: (code: string) => `${API_PATH.PROD_BRANDS}/${code}`,
		Restore: (code: string) => `${API_PATH.PROD_BRANDS}/restore/${code}`,
	},
	ProdTags: {
		Create: () => `${API_PATH.PROD_TAGS}/`,
		Single: (id: number) => `${API_PATH.PROD_TAGS}/${id}`,
		Many: () => `${API_PATH.PROD_TAGS}/`,
		Update: (id: number) => `${API_PATH.PROD_TAGS}/${id}`,
		Delete: (id: number) => `${API_PATH.PROD_TAGS}/${id}`,
		Restore: (id: number) => `${API_PATH.PROD_TAGS}/restore/${id}`,
	},
	ProdVariants: {
		Create: () => `${API_PATH.PROD_VARIANTS}/`,
		SingleByProdCode: (prod_code: string) => `${API_PATH.PROD_VARIANTS}/${prod_code}`,
		Many: () => `${API_PATH.PROD_VARIANTS}/`,
		Update: (id: number) => `${API_PATH.PROD_VARIANTS}/${id}`,
		Delete: (id: number) => `${API_PATH.PROD_VARIANTS}/${id}`,
		Restore: (id: number) => `${API_PATH.PROD_VARIANTS}/restore/${id}`,
	},
	ProdTypes: {
		Create: () => `${API_PATH.PROD_TYPES}/`,
		Single: (id: number) => `${API_PATH.PROD_TYPES}/${id}`,
		Many: () => `${API_PATH.PROD_TYPES}/`,
		Update: (id: number) => `${API_PATH.PROD_TYPES}/${id}`,
		Remove: (id: number) => `${API_PATH.PROD_TYPES}/${id}`,
		Restore: (id: number) => `${API_PATH.PROD_TYPES}/restore/${id}`,
	},
	ProdCategories: {
		Create: () => `${API_PATH.PROD_CATEGORIES}/`,
		Single: (code: string) => `${API_PATH.PROD_CATEGORIES}/${code}`,
		Many: () => `${API_PATH.PROD_CATEGORIES}/`,
		Update: (code: string) => `${API_PATH.PROD_CATEGORIES}/${code}`,
		Delete: (code: string) => `${API_PATH.PROD_CATEGORIES}/${code}`,
		Restore: (code: string) => `${API_PATH.PROD_CATEGORIES}/restore/${code}`,
	},
	ProdOptions: {
		Create: () => `${API_PATH.PROD_OPTIONS}/`,
		Single: (id: number) => `${API_PATH.PROD_OPTIONS}/${id}`,
		Many: () => `${API_PATH.PROD_OPTIONS}/`,
		Update: (id: number) => `${API_PATH.PROD_OPTIONS}/${id}`,
		Delete: (id: number) => `${API_PATH.PROD_OPTIONS}/${id}`,
		Restore: (id: number) => `${API_PATH.PROD_OPTIONS}/restore/${id}`,
	},
	Settings: {
		Many: () => `${API_PATH.SETTINGS}/`,
		Save: () => `${API_PATH.SETTINGS}/`,
	},
	CrmUsers: {
		Create: () => `${API_PATH.CRM_USERS}/`,
		Many: () => `${API_PATH.CRM_USERS}/`,
		Single: (id: string) => `${API_PATH.CRM_USERS}/${id}`,
		Update: (id: string) => `${API_PATH.CRM_USERS}/${id}`,
		UpdatePassword: (id: string) => `${API_PATH.CRM_USERS}/${id}/password`,
		Delete: (id: string) => `${API_PATH.CRM_USERS}/${id}`,
		Restore: (id: string) => `${API_PATH.CRM_USERS}/restore/${id}`,
	},
	Orders: {
		Many: () => `${API_PATH.ORDERS}`,
		Single: (order_no: string) => `${API_PATH.ORDERS}/${order_no}`,
		Update: (order_no: string) => `${API_PATH.ORDERS}/${order_no}`,
		UpdateOrderStatus: (order_no: string) => `${API_PATH.ORDERS}/${order_no}/status`,
		UpdateOrderCustomer: (order_no: string) => `${API_PATH.ORDERS}/${order_no}/customer`,
		UpdateOrderItems: (order_no: string) => `${API_PATH.ORDERS}/${order_no}/items`,
		UpdateOrderPayments: (order_no: string) => `${API_PATH.ORDERS}/${order_no}/payments`,
		Process: () => `${API_PATH.ORDERS}/process`,
		Export: () => `${API_PATH.ORDERS}/export`,
	},
	Sales: {
		Many: () => `${API_PATH.SALES}`,
		Single: (bill_no: string) => `${API_PATH.SALES}/${bill_no}`,
		Process: () => `${API_PATH.SALES}/process`,
		Export: () => `${API_PATH.SALES}/export`,
	},
	SummOrders: {
		Dashboard: () => `${API_PATH.SUMM_ORDERS}/dashboard`,
		Orders: () => `${API_PATH.SUMM_ORDERS}`,
		Export: () => `${API_PATH.SUMM_ORDERS}/export`,
		Items: () => `${API_PATH.SUMM_ORDERS}/items`,
		ExportItems: () => `${API_PATH.SUMM_ORDERS}/items/export`,
		Customers: () => `${API_PATH.SUMM_ORDERS}/customers`,
		ExportCustomers: () => `${API_PATH.SUMM_ORDERS}/customers/export`,
	},
	SummSales: {
		Dashboard: () => `${API_PATH.SUMM_SALES}/dashboard`,
		Sales: () => `${API_PATH.SUMM_SALES}`,
		Export: () => `${API_PATH.SUMM_SALES}/export`,
		Items: () => `${API_PATH.SUMM_SALES}/items`,
		ExportItems: () => `${API_PATH.SUMM_SALES}/items/export`,
		Payments: () => `${API_PATH.SUMM_SALES}/payments`,
		ExportPayments: () => `${API_PATH.SUMM_SALES}/payments/export`,
		Customers: () => `${API_PATH.SUMM_SALES}/customers`,
		ExportCustomers: () => `${API_PATH.SUMM_SALES}/customers/export`,
	},
	PaymentTypes: {
		Many: () => `${API_PATH.PAYMENT_TYPES}/`,
	},
	PaymentTypeGroups: {
		Many: () => `${API_PATH.PAYMENT_TYPE_GROUPS}/`,
	},
	PaymentMethods: {
		Many: () => `${API_PATH.PAYMENT_METHODS}/`,
		Update: (code: string) => `${API_PATH.PAYMENT_METHODS}/${code}`,
	},
	Appoinments: {
		Create: () => `${API_PATH.APPOINTMENTS}/`,
		Single: (code: string) => `${API_PATH.APPOINTMENTS}/${code}`,
		Many: () => `${API_PATH.APPOINTMENTS}/`,
		Update: (code: string) => `${API_PATH.APPOINTMENTS}/${code}`,
		Delete: (code: string) => `${API_PATH.APPOINTMENTS}/${code}`,
		Restore: (code: string) => `${API_PATH.APPOINTMENTS}/restore/${code}`,
	},
	Outlets: {
		Create: () => `${API_PATH.OUTLETS}/`,
		Many: () => `${API_PATH.OUTLETS}/`,
		Single: (code: string) => `${API_PATH.OUTLETS}/${code}`,
		Update: (code: string) => `${API_PATH.OUTLETS}/${code}`,
		Delete: (code: string) => `${API_PATH.OUTLETS}/${code}`,
		Restore: (code: string) => `${API_PATH.OUTLETS}/restore/${code}`,
	},
	Taxes: {
		Create: () => `${API_PATH.TAXES}/`,
		Many: () => `${API_PATH.TAXES}/`,
		Single: (code: string) => `${API_PATH.TAXES}/${code}`,
		Update: (code: string) => `${API_PATH.TAXES}/${code}`,
		Delete: (code: string) => `${API_PATH.TAXES}/${code}`,
		Restore: (code: string) => `${API_PATH.TAXES}/restore/${code}`,
	},
	TaxGroups: {
		Create: () => `${API_PATH.TAX_GROUPS}/`,
		Many: () => `${API_PATH.TAX_GROUPS}/`,
		Single: (code: string) => `${API_PATH.TAX_GROUPS}/${code}`,
		Update: (code: string) => `${API_PATH.TAX_GROUPS}/${code}`,
		Delete: (code: string) => `${API_PATH.TAX_GROUPS}/${code}`,
		Restore: (code: string) => `${API_PATH.TAX_GROUPS}/restore/${code}`,
	},
	TaxRules: {
		Create: () => `${API_PATH.TAX_RULES}/`,
		Many: () => `${API_PATH.TAX_RULES}/`,
		Single: (code: string) => `${API_PATH.TAX_RULES}/${code}`,
		Update: (code: string) => `${API_PATH.TAX_RULES}/${code}`,
		Delete: (code: string) => `${API_PATH.TAX_RULES}/${code}`,
		Restore: (code: string) => `${API_PATH.TAX_RULES}/restore/${code}`,
	},
};
